### ISSUE TITLE
Unable to validate location preferences 

### ISSUE THREAD

**Issue by eabyanks** [Unidata/awips2#191] opened 2017-08-26 15:20 UTC
Hello. I am trying to install CAVE for my MacBook Air. I can't connect to the EDEX server. I keep on getting an error, "unable to validate location preferences." Any help would be appreciated. Thanks.﻿

**Comment by mjames-upc** [comment] 2017-08-28 17:18
duplicate of #183

**Closed as completed by mjames-upc** 2017-08-28 17:18 UTC
