### ISSUE TITLE
How do I get dropdown menus for individual radar sites in 17.1.1?

### ISSUE THREAD

**Issue by airbusman5514** [Unidata/awips2#186] opened 2017-07-20 15:29 UTC
Is there a way to get dropdown menus for individual radar sites in the top menu bar? A link to what I'm looking for is included.

[https://nasasport.files.wordpress.com/2013/03/lma-2042.png](url)

Thanks!

**Comment by mjames-upc** [comment] 2018-06-11 19:17
Duplicate of #219

**Closed as completed by mjames-upc** 2018-06-11 19:17 UTC
